name: .NET

on:
  push:
    branches: [ "mains" ]

env:
  DOTNET_APP_NAME: dotnet-application
  DOTNET_ENV_NAME: dotnet-application-dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0

      - name: Restore dependencies
        run: dotnet restore src

      - name: Build
        run: dotnet build src --no-restore

      - name: Test
        run: dotnet test src --no-build --verbosity normal

      - name: Publish
        run: dotnet publish src -c Release -o website -r linux-x64 --self-contained false

      - name: Zip deployment package
        run: cd website; zip -r ../deployment-package.zip .; cd ..

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ env.DOTNET_APP_NAME }}
          environment_name: ${{ env.DOTNET_ENV_NAME }}
          use_existing_version_if_available: true
          version_label: "version-${{ github.run_id }}"
          region: ${{ secrets.AWS_DEFAULT_REGION }}
          deployment_package: deployment-package.zip

      - name: Deployed
        run: echo '______ App deployed to ELB ______'
